#! /usr/bin/env node


import inquirer from "inquirer";

// 1) Computer will generarte a random number

// 2) User input for guessing number

// 3) Compare user input with computer generated number and show result

const randomNumber = Math.floor(Math.random() * 5 + 1 ); //Math.random is for generating random numbers in decimal and Math.floor for making numbers roundof of numbers generated by Math.random. * 10 means maximum random number will be less than 10 and then we have added 1 in the random number


const answers = await inquirer.prompt([
  {
    name: "UserGuessedNumber", //here name is always in small letters otherwise it will give error
    type: "number", //here type is always in small letters otherwise it will give error
    message: "Please guess a number between 1-5", //here message is always in small letters otherwise it will give error
  },
]);

if (answers.UserGuessedNumber === randomNumber) {
  //here === is must
  console.log("Congratulation! you guessed right number.");
} else {
  console.log("You guessed wrong number");
}
